name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Déclencher le workflow uniquement pour les pushs sur la branche main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./portfoliot-front/Dockerfile  # chemin du docker file
          push: true
          tags: rafik1212/back-porfoliot
